# Order Dataset

## Load Required Libraries

In [56]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import os

from pathlib import Path

### Optional Display Settings

In [57]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [58]:
print(os.getcwd())  # Prints the current working directory

/home/david/Personal-Project/olist-data-analytics/notebooks

## Read Raw Data

In [5]:

orders_df = pd.read_csv("../data/raw/orders.csv")
order_items_df = pd.read_csv("../data/raw/order_items.csv")
order_payments_df = pd.read_csv("../data/raw/order_payments.csv")
order_reviews_df = pd.read_csv("../data/raw/order_reviews.csv")
products_df = pd.read_csv("../data/raw/products.csv")
product_category_name_translation_df = pd.read_csv("../data/raw/product_category_name_translation.csv")
sellers_df = pd.read_csv("../data/raw/sellers.csv")
customers_df = pd.read_csv("../data/raw/customers.csv")
geolocation_df = pd.read_csv("../data/raw/geolocation.csv")

## Create a Copy of the Raw Data

In [6]:

orders_df_clean = orders_df.copy()
order_items_df_clean = order_items_df.copy()
order_payments_df_clean = order_payments_df.copy()
order_reviews_df_clean = order_reviews_df.copy()
products_df_clean = products_df.copy()
product_category_name_translation_dfc_lean = product_category_name_translation_df.copy()
sellers_df_clean = sellers_df.copy()
customers_df_clean = customers_df.copy()
geolocation_df_clean = geolocation_df.copy()

## Initial Data Validation

In [7]:

print(f"ORDERS SHAPE")
orders_df_clean.shape

print(f"\n ORDERS INFO")
orders_df_clean.info()

print(f"\n ORDERS HEAD")
print(orders_df_clean.head(6))

print(f"\n ORDERS DESCRIPTION")
orders_df_clean.describe(include="all")

ORDERS SHAPE

 ORDERS INFO
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 21.9 MB

 ORDERS HEAD
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c
5  a4591c265e18cb1dcee52889e2d8acc3  503740e9ca751ccdda7ba28e9ab8f608

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29
5    delivered      2017-07-09 21:57:05  2017-07-09 22:10:13

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02
5          2017-07-11 14:58:04           2017-07-26 10:57:55

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00
3           2017-12-15 00:00:00
4           2018-02-26 00:00:00
5           2017-08-01 00:00:00

 ORDERS DESCRIPTION

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-03-31 15:08:21,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

## standardize column name

In [8]:

orders_df_clean.columns = (
    orders_df_clean.columns
    .str.strip()
    .str.lower()
)

orders_df_clean.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

## Fix Data Types

In [9]:

data_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

orders_df_clean[data_cols] = orders_df_clean[data_cols].apply(pd.to_datetime)


# Convert order_status to category column
orders_df_clean["order_status"] = (orders_df_clean["order_status"]).astype("category")

# check the datatype
orders_df_clean.dtypes

order_id                                    str
customer_id                                 str
order_status                           category
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

## Remove Duplicate Rows

In [10]:

orders_df_clean.duplicated().sum() # check if a row duplicate exist
orders_df_clean["order_id"].duplicated().sum() # check if the primary key has a duplicate

if orders_df_clean.duplicated().sum() > 1 or orders_df_clean["order_id"].duplicated().sum() > 1:
    orders_df_clean = orders_df_clean.drop_duplicates()

## Check for Missing Values

In [11]:
orders_df_clean.isna().sum() # checks the entire data frame to find null or empty cells in any of the columns and return the count value

orders_df_clean.isna().mean().mul(100).sort_values(ascending=False) # find the percentage of missing values

order_delivered_customer_date    2.981668
order_delivered_carrier_date     1.793023
order_approved_at                0.160899
order_id                         0.000000
order_purchase_timestamp         0.000000
order_status                     0.000000
customer_id                      0.000000
order_estimated_delivery_date    0.000000
dtype: float64

## Investigate Missing Values

In [ ]:
#create Boolean masks for each timestamp
purchase_exists = orders_df_clean["order_purchase_timestamp"].notna() # filter the row and keep only the rows where a value exists in order_chase_timestamp column
approved_exists = orders_df_clean["order_approved_at"].notna() # filter th e row keep only the rows where a value exists in order_approved_at column
carrier_exists = orders_df_clean["order_delivered_carrier_date"].notna() # filter the row keep only the rows where a value exists in order_delivered_carrier_date column
customer_exists = orders_df_clean["order_delivered_customer_date"].notna() # filter the row keep only the rows where a value exists in order_delivered_customer_date column
estimated_exists = orders_df_clean["order_estimated_delivery_date"].notna() # filter the row keep only the rows where a value exists in order_estimated_delivery_date column

# print(f"\npurchase_exists\n{purchase_exists}")
# print(f"\napproved_exists\n{approved_exists}")
# print(f"\ncarrier_exists\n{carrier_exists}")
# print(f"\ncustomer_exists\n{customer_exists}")
# print(f"\nestimated_exists\n{estimated_exists}")

#get the order status
status = orders_df_clean["order_status"]
# print(f"ORDER STATUS\n", status)

# Finding bad and inconsistent data by creating a bolean mask
# and ensure each anomaly contains only rows where the anomaly condition is true.
delivered_anomalies = orders_df_clean[
    (status == "delivered") &
    (
        ~purchase_exists |
        ~approved_exists |
        ~carrier_exists |
        ~customer_exists |
        ~estimated_exists
    )
]

shipped_anomalies = orders_df_clean[
    (status == "shipped") &
    (
        ~purchase_exists |
        ~approved_exists |
        ~carrier_exists |
        ~estimated_exists
    )
]

approved_anomalies = orders_df_clean[
    (status == "approved") &
    (
        ~purchase_exists |
        ~approved_exists |
        ~estimated_exists
    )
]

processing_anomalies = orders_df_clean[
    (status == "processing") &
    (
        ~purchase_exists |
        ~approved_exists |
        ~estimated_exists
    )
]

invoiced_anomalies = orders_df_clean[
    (status == "invoiced") &
    (
        ~purchase_exists |
        ~approved_exists |
        ~estimated_exists
    )
]


canceled_anomalies = orders_df_clean[
    (status == "canceled") &
    (
        ~purchase_exists |
        ~estimated_exists |
        carrier_exists |
        customer_exists
    )
]

unavailable_anomalies = orders_df_clean[
    (status == "unavailable") &
    (
        ~purchase_exists |
        ~approved_exists |
        ~estimated_exists
    )
]

# put all the anomaly rows from different statuses into one DataFrame and
# removes any repeated rows if the same order happened to be included more than once
anomalies = pd.concat([
    delivered_anomalies,
    shipped_anomalies,
    approved_anomalies,
    processing_anomalies,
    invoiced_anomalies,
    canceled_anomalies,
    unavailable_anomalies
]).drop_duplicates()

print("anomalies: ")
print(anomalies)


len(anomalies)
# anomalies.shape

anomalies[
    [
        "order_status",
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ]
]

## Handle Missing Values

## Check Invalid Values

In [ ]:
# check for order_ids that contain a date pattern so that the dataFrame is filetered to contain only rows that meet the condition inside the block bracket of the dataFrame.
orders_df_clean[
    orders_df_clean["customer_id"].str.contains(r"\d{4}-\d{2}-\d{2}", regex=True, na=False)
]
orders_df_clean[
    orders_df_clean["order_id"].str.contains(r"\d{4}-\d{2}-\d{2}", regex=True, na=False)
]

# the length of every coulmn data
orders_df_clean["customer_id"].str.len().value_counts()
orders_df_clean["order_id"].str.len().value_counts()


# Check for non-hexadecimal characters
orders_df_clean[
    ~orders_df_clean["order_id"].str.fullmatch(r"[0-9a-f]{32}", na=False)
]
orders_df_clean[
    ~orders_df_clean["customer_id"].str.fullmatch(r"[0-9a-f]{32}", na=False)
]


# Check for the data_type
orders_df_clean["order_purchase_timestamp"].dtypes
orders_df_clean["order_delivered_carrier_date"].dtypes
orders_df_clean["order_approved_at"].dtypes
orders_df_clean["order_delivered_customer_date"].dtypes
orders_df_clean["order_estimated_delivery_date"].dtypes

dtype('<M8[us]')

## Standardize Categories

In [ ]:
#standardise the values of the order_status columns
orders_df_clean["order_status"] = orders_df_clean["order_status"].str.lower().str.strip()

orders_df_clean["order_status"].dtypes
orders_df_clean[data_cols].dtypes

dtype('O')

## Check Logical Consistency

In [34]:
# Define the order lifecycle columns
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

# Ensure they are datetime
orders_df_clean[date_columns] = orders_df_clean[date_columns].apply(pd.to_datetime)

# -----------------------------
# Logical consistency checks
# -----------------------------

# 1. Approval before Purchase (should never happen)
approval_before_purchase = (
    orders_df_clean["order_approved_at"]
    < orders_df_clean["order_purchase_timestamp"]
)

print("Approval before Purchase\n")
print(approval_before_purchase.head())

# 2. Carrier Pickup before Approval (should not happen)
carrier_before_approval = (
    orders_df_clean["order_delivered_carrier_date"]
    < orders_df_clean["order_approved_at"]
)
print("Carrier Pickup before Approval\n")
print(carrier_before_approval.head())

# 3. Customer Delivery before Carrier Pickup (should not happen)
delivery_before_carrier = (
    orders_df_clean["order_delivered_customer_date"]
    < orders_df_clean["order_delivered_carrier_date"]
)
print("Customer Delivery before Carrier Pickup\n")
print(delivery_before_carrier.head())

# 4. Estimated Delivery before Purchase
estimated_before_purchase = (
    orders_df_clean["order_estimated_delivery_date"]
    < orders_df_clean["order_purchase_timestamp"]
)

print("Estimated Delivery before Purchase\n")
print(estimated_before_purchase.head())

# -----------------------------
# Summary
# -----------------------------

print(f"Approval before Purchase: {approval_before_purchase.sum()}")
print(f"Carrier Pickup before Approval: {carrier_before_approval.sum()}")
print(f"Customer Delivery before Carrier Pickup: {delivery_before_carrier.sum()}")
print(f"Estimated Delivery before Purchase: {estimated_before_purchase.sum()}")

Approval before Purchase

0    False
1    False
2    False
3    False
4    False
dtype: bool
Carrier Pickup before Approval

0    False
1    False
2    False
3    False
4    False
dtype: bool
Customer Delivery before Carrier Pickup

0    False
1    False
2    False
3    False
4    False
dtype: bool
Estimated Delivery before Purchase

0    False
1    False
2    False
3    False
4    False
dtype: bool
Approval before Purchase: 0
Carrier Pickup before Approval: 1359
Customer Delivery before Carrier Pickup: 23
Estimated Delivery before Purchase: 0

#### view the problematic records

In [ ]:
# Approval before Purchase
orders_df_clean.loc[
    approval_before_purchase,
    [
        "order_id",
        "order_purchase_timestamp",
        "order_approved_at"
    ]
]

# Carrier Pickup before Approval
# orders_df_clean.loc[
#     carrier_before_approval,
#     [
#         "order_id",
#         "order_approved_at",
#         "order_delivered_carrier_date"
#     ]
# ]

# Customer Delivery before Carrier Pickup
orders_df_clean.loc[
    delivery_before_carrier,
    [
        "order_id",
        "order_delivered_carrier_date",
        "order_delivered_customer_date"
    ]
]

# Estimated Delivery before Purchase
orders_df_clean.loc[
    estimated_before_purchase,
    [
        "order_id",
        "order_purchase_timestamp",
        "order_estimated_delivery_date"
    ]
]

#### Calculate time difference

In [32]:
# Carrier before Approval
carrier_issue = orders_df_clean.loc[carrier_before_approval].copy()

carrier_issue["difference"] = (
    carrier_issue["order_approved_at"]
    - carrier_issue["order_delivered_carrier_date"]
)

carrier_issue["difference"].describe()


# Delivery before Carrier
delivery_issue = orders_df_clean.loc[delivery_before_carrier].copy()

delivery_issue["difference"] = (
    delivery_issue["order_delivered_carrier_date"]
    - delivery_issue["order_delivered_customer_date"]
)

delivery_issue["difference"].describe()

count                        23
mean     3 days 06:27:18.478260
std      3 days 17:18:29.050924
min             0 days 00:23:18
25%             0 days 23:20:18
50%             1 days 15:51:52
75%      5 days 08:45:32.500000
max            16 days 02:18:29
Name: difference, dtype: object

#### Check the Order Status

In [31]:
# Carrier before Approval
orders_df_clean.loc[
    carrier_before_approval,
    "order_status"
].value_counts()

# Delivery before Carrier
# orders_df_clean.loc[
#     delivery_before_carrier,
#     "order_status"
# ].value_counts()

order_status
delivered    1350
shipped         9
Name: count, dtype: int64

#### Creating Flag

In [33]:
orders_df_clean["flag_carrier_before_approval"] = carrier_before_approval

orders_df_clean["flag_delivery_before_carrier"] = delivery_before_carrier

orders_df_clean["timeline_valid"] = ~(
    carrier_before_approval |
    delivery_before_carrier
)

## Feature Engineering

#### Engineer numerical features from the timestamps

In [47]:
orders_df_clean.describe()

# Create a column called approval_time_hours that tells how many hours it took for payment to be approved
orders_df_clean["approval_time_hours"] = (
    orders_df_clean["order_approved_at"]
    - orders_df_clean["order_purchase_timestamp"]
).dt.total_seconds() / 3600

# Create a column called shipping_time_days that tells how many days it took to ship an order
orders_df_clean["shipping_time_days"] = (
    orders_df_clean["order_delivered_carrier_date"]
    - orders_df_clean["order_approved_at"]
).dt.days.astype("Int64")

# Create a column called shipping_time_days that tells us how many days it took for the order to get to the buyer
orders_df_clean["delivery_time_days"] = (
    orders_df_clean["order_delivered_customer_date"]
    - orders_df_clean["order_delivered_carrier_date"]
).dt.days.astype("Int64")

orders_df_clean["total_fulfillment_days"] = (
    orders_df_clean["order_delivered_customer_date"]
    - orders_df_clean["order_purchase_timestamp"]
).dt.days.astype("Int64")

## Detecting Outliers

In [41]:
# Find the Number of Outliers present in delivery_time_days column
Q1 = orders_df_clean["delivery_time_days"].quantile(0.25)
Q3 = orders_df_clean["delivery_time_days"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

delivery_outliers = orders_df_clean[
    (orders_df_clean["delivery_time_days"] < lower) |
    (orders_df_clean["delivery_time_days"] > upper)
]

print(f"Outliers: {len(delivery_outliers)}")


# Find the Number of Outliers present in delivery_time_days column
Q1 = orders_df_clean["approval_time_hours"].quantile(0.25)
Q3 = orders_df_clean["approval_time_hours"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

approval_time_outliers = orders_df_clean[
    (orders_df_clean["approval_time_hours"] < lower) |
    (orders_df_clean["approval_time_hours"] > upper)
]

print(f"Outliers: {len(approval_time_outliers)}")


# Find the Number of Outliers present in delivery_time_days column
Q1 = orders_df_clean["shipping_time_days"].quantile(0.25)
Q3 = orders_df_clean["shipping_time_days"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

shipping_outliers = orders_df_clean[
    (orders_df_clean["shipping_time_days"] < lower) |
    (orders_df_clean["shipping_time_days"] > upper)
]

print(f"Outliers: {len(shipping_outliers)}")


# Find the Number of Outliers present in delivery_time_days column
Q1 = orders_df_clean["total_fulfillment_days"].quantile(0.25)
Q3 = orders_df_clean["total_fulfillment_days"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

total_fulfillment_days_outliers = orders_df_clean[
    (orders_df_clean["total_fulfillment_days"] < lower) |
    (orders_df_clean["total_fulfillment_days"] > upper)
]

print(f"Outliers: {len(total_fulfillment_days_outliers)}")

Outliers: 4552
Outliers: 9141
Outliers: 5082
Outliers: 5025

## Validate Everything Again

In [ ]:
# Confirm the information about the table
orders_df_clean.info()

# Confirm the statistical review of the cleaned table
orders_df_clean.describe(include="all")

# Confirm the number of rows in the table contain a missing value
orders_df_clean.isna().sum()

# Confirm if there is still a duplicated row
orders_df_clean.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 15 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
 8   flag_carrier_before_approval   99441 non-null  bool
 9   flag_delivery_before_carrier   99441 non-null  bool
 10  timeline_valid                 99441 non-null  bool
 11  approval_time_hours            99281 non-null  float64
 12  shipping_time_days             97644 non-null  Int64
 13  delivery_time_days             96475 non-null  Int64
 14  total_fulfillment_days         96476 non-null  Int64
dtypes: Int64(3), bool(3), datetime64[us](5), float64(1), object(1), str(2)
memory usage: 15.7+ MB

,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
order_status,,,
approved,0,2,2
canceled,141,550,619
created,5,5,5
delivered,14,2,8
invoiced,0,314,314
processing,0,301,301
shipped,0,0,1107
unavailable,0,609,609

## Save Clean Data

In [ ]:
orders_df_clean.to_csv(
    "../data/cleaned/orders_clean.csv",
    index=False
)

# Order Items Dataset